#!/bin/bash
# Usage: script/cibuild
# CI build script

set -e

# setup environment
test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}

# GC customizations
export RUBY_GC_MALLOC_LIMIT=79000000
export RUBY_HEAP_MIN_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=400000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1

export RAILS_ROOT=$(cd "$(dirname $0)"/.. && pwd)
export RAILS_ENV="test"
export RACK_ROOT="$RAILS_ROOT"
export RACK_ENV="$RAILS_ENV"
export RBENV_VERSION="1.9.3-p448"

# clean out the ruby environment
export RUBYLIB=
export RUBYOPT=

echo "hostname: $(hostname)"
echo "ruby version: $(ruby -v)"

# bootstrap gem environment changes
cd "$RAILS_ROOT"
bundle install --quiet --binstubs --local --path vendor/gems

bundle exec rake db:drop db:create RAILS_ENV=test
bundle exec rake test
