#!/bin/sh

set -e

test -f .env || {
  echo "You need a .env file present! Currently missing one."
  exit 1
}

test -z "$GH_SOCKET_DIR" && {
  echo "Can't start: GH_SOCKET_DIR isn't set."
  echo "\033[31mUsing original server script.\033[0m"
  script/server.orig
  exit 1
}

test -z "$RACK_ENV" &&
  RACK_ENV='development'

RAILS_ENV=$RACK_ENV bin/unicorn_rails -E $RACK_ENV -c config/unicorn.rb
